// Bilingual UI chrome strings for the interactive components.
// Question/guide *content* is bilingual in the data itself; these are the labels.

export const UI = {
  en: {
    // quiz
    allScenarios: 'All scenarios',
    onlyIncorrect: 'Only incorrect',
    onlyBookmarked: 'Only bookmarked',
    shuffleLabel: 'Shuffle',
    bookmark: 'Bookmark',
    keyHint: '←/→ navigate · 1–4 answer · B bookmark',
    showSecondary: 'Show 中文',
    hideSecondary: 'Hide 中文',
    question: 'Question',
    correct: 'Correct',
    incorrect: 'Incorrect',
    why: 'Why',
    prev: '← Prev',
    next: 'Next →',
    resetProgress: 'Reset progress',
    resetConfirm: 'Reset all saved answers?',
    answered: 'Answered',
    accuracy: 'Accuracy',
    noMatch: 'No questions match this filter.',
    yourAnswer: 'Your answer',
    // exam
    startExam: 'Start mock exam',
    examIntro:
      'The real exam: 60 questions drawn from 4 of 8 scenarios, scored 100–1000 (pass: 720). This mock mirrors that: a timed set with a scaled score.',
    questionsLabel: 'questions',
    minutes: 'min',
    submit: 'Submit exam',
    timeLeft: 'Time left',
    finish: 'Finish & review',
    examResult: 'Exam result',
    score: 'Score',
    passed: 'PASSED',
    failed: 'NOT PASSED',
    retake: 'Retake',
    byScenario: 'By scenario',
    history: 'Your past attempts',
    reviewAttempt: 'Review',
    viewingPast: 'Reviewing a past attempt',
    backToStart: '← Back',
    // flashcards
    flip: 'Flip',
    again: 'Again',
    hard: 'Hard',
    good: 'Good',
    easy: 'Easy',
    dueToday: 'Due today',
    newCard: 'New',
    allDone: 'All caught up — no cards due. 🎉',
    resetCards: 'Reset cards',
    showAnswer: 'Show answer',
    deck: 'Deck',
    allDecks: 'All decks',
    newToday: 'New today',
    // dashboard
    overallAccuracy: 'Overall accuracy',
    answeredOf: 'answered of',
    perScenario: 'Accuracy by scenario',
    notStarted: 'Not started',
    weakest: 'Focus here',
    practice: 'Practice',
    noData: 'No practice data yet — answer some questions first.',
    scoreTrend: 'Mock-exam score trend',
    streakLabel: 'Day streak',
    cardsDue: 'Cards due',
    cardsLearned: 'learned',
    // glossary
    search: 'Search terms…',
    term: 'Term',
    noTerms: 'No matching terms.',
    // data backup
    dataSection: 'Your data',
    exportData: 'Export backup',
    importData: 'Import backup',
    resetAllData: 'Reset everything',
    resetAllConfirm: 'Delete ALL saved progress, exam history, and flashcard state on this device?',
    importBad: 'Not a valid backup file.',
    dataHint: 'Progress is stored in this browser only — export a backup to move it to another device.',
  },
  'zh-tw': {
    // quiz
    allScenarios: '所有情境',
    onlyIncorrect: '只看答錯',
    onlyBookmarked: '只看書籤',
    shuffleLabel: '隨機順序',
    bookmark: '書籤',
    keyHint: '←/→ 切換 · 1–4 作答 · B 書籤',
    showSecondary: '顯示 English',
    hideSecondary: '隱藏 English',
    question: '問題',
    correct: '答對',
    incorrect: '答錯',
    why: '為何',
    prev: '← 上一題',
    next: '下一題 →',
    resetProgress: '重設進度',
    resetConfirm: '要清除所有已儲存的作答嗎?',
    answered: '已作答',
    accuracy: '正確率',
    noMatch: '沒有符合此篩選的題目。',
    yourAnswer: '你的答案',
    // exam
    startExam: '開始模擬考',
    examIntro:
      '正式考試:從 8 個情境隨機抽 4 個、共 60 題,以 100–1000 計分(及格 720)。此模擬考比照辦理:計時作答並換算分數。',
    questionsLabel: '題',
    minutes: '分鐘',
    submit: '交卷',
    timeLeft: '剩餘時間',
    finish: '結束並檢討',
    examResult: '考試結果',
    score: '分數',
    passed: '通過',
    failed: '未通過',
    retake: '再考一次',
    byScenario: '依情境',
    history: '你的歷次紀錄',
    reviewAttempt: '檢視',
    viewingPast: '正在檢視歷史考卷',
    backToStart: '← 返回',
    // flashcards
    flip: '翻面',
    again: '重來',
    hard: '困難',
    good: '普通',
    easy: '容易',
    dueToday: '今日待複習',
    newCard: '新卡',
    allDone: '全部複習完畢 —— 今天沒有待複習的卡片。🎉',
    resetCards: '重設字卡',
    showAnswer: '顯示答案',
    deck: '牌組',
    allDecks: '全部牌組',
    newToday: '今日新卡',
    // dashboard
    overallAccuracy: '整體正確率',
    answeredOf: '已作答 /',
    perScenario: '各情境正確率',
    notStarted: '尚未開始',
    weakest: '優先加強',
    practice: '練習',
    noData: '尚無練習資料 —— 先去作答一些題目吧。',
    scoreTrend: '模擬考成績趨勢',
    streakLabel: '連續學習天數',
    cardsDue: '字卡待複習',
    cardsLearned: '已學習',
    // glossary
    search: '搜尋術語…',
    term: '術語',
    noTerms: '沒有符合的術語。',
    // data backup
    dataSection: '你的資料',
    exportData: '匯出備份',
    importData: '匯入備份',
    resetAllData: '全部重置',
    resetAllConfirm: '刪除此裝置上所有已儲存的進度、考試紀錄與字卡狀態?',
    importBad: '不是有效的備份檔。',
    dataHint: '進度只儲存在這個瀏覽器 —— 匯出備份即可搬到其他裝置。',
  },
};

export const t = (lang, key) => (UI[lang] || UI.en)[key] ?? (UI.en[key] ?? key);
